### PR TITLE
fix: Include all columns in full data download

### LINKED ISSUE #1416: Download Full xls : Dimensions are missing
Some Dimensions (dimensions that are not Key dimensions) are missing by download Full dataset on Visualize INT 

**To Reproduce**
1. Open https://www.visualize.admin.ch/en/v/t6ee4XGN_Ofz
2. Download Full datset in csv and in xls
3. look at Columns : They are 8 Columns
4. Opne same cube on INT : https://int.visualize.admin.ch/en/v/8m_Dl0WtYvjx
5. Download Full datset in csv and in xls
6. look at Columns : 4 columns are missing

**Expected behavior**
By Download "Full Dataset" all Dimensions which are integreted in the cube must be downloaded. See Behaviour on PROD with same Cube. 

**Screenshots or video**
Download with PROD :
image

Download same Cube with INT
image

**Environment (please complete the following information):**

- Visualize environment and version:v3.27.1 [8c3e7f9]
- Browser and version : Edge

**Additional context**

### PR DESCRIPTION
**Pull request by bprusinowski**
Closes #1416

### CODE REVIEW

File: app/components/chart-footnotes.tsx [hunk 1]
```diff
@@ -211,7 +211,10 @@ export const ChartFootnotes = ({
                     <DataDownloadMenu
                       dataSource={dataSource}
                       title={dataCubeMetadata.title}
-                      filters={filters}
+                      filters={
+                        filters ??
+                        chartConfig.cubes.map((cube) => ({ iri: cube.iri }))
+                      }
```
Comment (ptbrowne) [inline app/components/chart-footnotes.tsx:217]: Not sure I understand this ? Shouldn't we also "mix" the filters with the cubes ?

Comment (ptbrowne) [reply app/components/chart-footnotes.tsx:217]: Here we do not use getFullDataDownloadFilters  ?

Comment (bprusinowski) [reply app/components/chart-footnotes.tsx:217]: Hmmm, here we either pass `filters` if they are present, or "construct" them in case they are missing. In `getFullDataDownloadFilters` we need to pass `filters` as an argument, so couldn't apply this to `chartConfig.cubes.map((cube) => ({ iri: cube.iri }))`. Let me know if it makes sense or if I missed something 👀

Comment (bprusinowski) [reply app/components/chart-footnotes.tsx]: I refactored a bit to introduce a new function, let me know if it makes more sense now @ptbrowne 🙇‍♂️

File: app/components/data-download.tsx [hunk 2]
```diff
@@ -252,12 +252,9 @@ const DataDownloadInnerMenu = ({
...
           subheader={<Trans id="button.download.data.all">Full dataset</Trans>}
           fileName={`${fileName}-full`}
-          filters={filters?.map((d) => {
-            return {
-              iri: d.iri,
-              componentIris: d.componentIris,
-            };
-          })}
+          // We need to include every cube column in full dataset download (client's
+          // request), so we do not pass any filters here.
```
Comment (ptbrowne) [inline app/components/data-download.tsx]: `we do not pass any componentIris here` ?

File: app/components/data-download.spec.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
+import { RDFCubeViewQueryMock } from "@/test/cube-view-query-mock";
+RDFCubeViewQueryMock;
+
+// eslint-disable-next-line import/order
+import get from "lodash/get";
```
Comment (ptbrowne) [inline app/components/data-download.spec.ts:5]: For my information, why do we need to disable import/order here ?

Comment (bprusinowski) [reply app/components/data-download.spec.ts:1]: That's a good question, it had to do with the order of mocking things – in some tests, this mock had to be the first thing that's mocked, which clashes with the default import order we define via eslint. In fact, I believe it makes more sense to include this mock in jest setup – I adjusted this in https://github.com/visualize-admin/visualization-tool/pull/1420/commits/7dfce84e672dab5e816e434037d797e98581b200 👀

Comment (ptbrowne) [reply app/components/data-download.spec.ts:1]: Looks good, thanks 👍

**Review by ptbrowne — APPROVED** [review]
Thanks 👍

**Comment by bprusinowski** [comment]
Merging to `main`, as failed CI E2E tests work fine locally.
