### PR TITLE
Fix/smaller improvements

### LINKED ISSUE #1758: Allow User to Copy Share Link from User Profile
At the moment, if the user selects "share" on a published chart in the user profile, they are taken to the published view where they can then click the "share" button, and copy the URL. 
I think this behaviour could be confusing for someone who is using visualize for the first time, as they then have to find the share button in UI of the published view to copy the URL. I think it would be a nice enhancement to allow the user to copy the published chart link,  and possibly even the embedd code directly from the user profile, as oppose to having them first open the published view. 

https://github.com/user-attachments/assets/53e9b63d-59fb-41aa-b4dc-99d5acb0aa85

### LINKED ISSUE #1800: Improve visibility of selected data set
**Issue**
Users get lost in the visualization view after selecting a data set - as there was no reference to the data selected (in Editor Mode)

-    Idea: Use as the title for the data set
-    Idea: Add under “Zurück zu Vorschau"

**To consider**
- Users may not understand that the title can be changed / where it is coming from.
- With Dashboards it gets more complex.
 
Similar Feedback from Tobias: https://github.com/visualize-admin/visualization-tool/issues/1172

### LINKED ISSUE #1818: Switch Button and Y-Axis Title Overlap in Interactive Chart Mode
**Describe the bug** 
Wenn making the Chart mode (normal or 100%) interactive, the switch button and the title of the y-axis overlap.

**To Reproduce** Steps to reproduce the behavior:

1. Go to any project (e.g.: [visualize](https://visualize.admin.ch/en/browse?previous=%7B%22type%22%3A%22organization%22%2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-lebensmittelsicherheit-und-veterinaerwesen-blv%22%2C%22topic%22%3A%22%22%7D&dataset=https%3A%2F%2Fhealth.ld.admin.ch%2Ffsvo%2FBT_entwicklung%2F13&dataSource=Prod))
2. Start a new visualisation
3. Select "Columns" or "Areas" as the chart type.
4. Add a segmentation column in the Chart options.
5. Change the Chart mode to interactive
6. Observe the overlapping elements.

**Expected behavior** 
The switch button and the y-axis title should appear one below the other without overlapping.

**Screenshots or video** 
Image

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.9.3
- Browser and version: Microsoft Edge v130.0.2849.56

### PR DESCRIPTION
**Pull request by noahonyejese**
This PR resolves #1818 , resolves #1800 and resolves #1758
- This PR adds sharing and embedding capabilities directly into the users profile 
- This PR improves the visibiliy current dataset used in during Visualization Creation 
- This PR resolves the overlapping bug when using interactive Filters

### Next Steps
1. @KerstinFaye please provide a design for #1800 and #1758 like this I can proceed. More details about ideas from the Team you can find under the Issue's themselves ✅

---

### How to Test (1800)
1. Go to this [Link](https://vercel.live/open-feedback/visualization-tool-git-fix-smaller-improvements-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)
2. Create a Visualization (f.e Einmalvergütung für Photovoltaikanlagen)
3. See how the Data Sources Section is Called Datasets ✅
4. See how the Datasets Section is all the way on the top ✅
5. See how button styling within the Datasets Section changed from outlined to text ✅

---

### How to Test (1818)
1. Go to this [Link](https://vercel.live/open-feedback/visualization-tool-git-fix-smaller-improvements-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1) 
2. Create a new Visualization 
3. Select "Columns" or "Areas" as the chart type.
4. Add a segmentation column in the Chart options.
5. Change the Chart mode to interactive
6. Observe the overlapping elements.

> Test how it was before 
> old Issue [Link](https://visualize.admin.ch/en/browse?previous=%7B%22type%22%3A%22organization%22%2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-lebensmittelsicherheit-und-veterinaerwesen-blv%22%2C%22topic%22%3A%22%22%7D&dataset=https%3A%2F%2Fhealth.ld.admin.ch%2Ffsvo%2FBT_entwicklung%2F14&dataSource=Prod)

---

### How to Test (1758)
- #1758 can only be tested once deployed, I will be providing a video soon

### CODE REVIEW

**Comment by sosiology** [comment]
@noahonyejese thanks bug with the interactive filters LGTM! 👏

Will test: 
- sharing and embedding capabilities directly into the users profile once on TEST as i cannot login to my profile on a PR 
- visibiliy current dataset used in during Visualization Creation once it is implemented as designed.

**Comment by noahonyejese** [comment]
> @noahonyejese thanks bug with the interactive filters LGTM! 👏
> 
> Will test:
> 
> * sharing and embedding capabilities directly into the users profile once on TEST as i cannot login to my profile on a PR
> * visibiliy current dataset used in during Visualization Creation once it is implemented as designed.

Hi @sosiology the #1800 is implemented based on @KerstinFaye [design](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5255-46027&node-type=frame&m=dev)  Please feel free to compare.

**Comment by noahonyejese** [comment]
Proposals: @KerstinFaye should we remove the Beta flag or the notification (1) from the section I think especially the (1) is drawing enormous attention towards it causing it to be opened even tho this may not be something the user will want to use straight away?

File: app/charts/shared/containers.tsx [hunk 1]
```diff
@@ -22,6 +22,8 @@ export const useStyles = makeStyles<{}, {}, "chartContainer">(() => ({
   },
 }));
 
+const INTERACTIVE_TOGGLE_SPACING = 20;
```
Comment (bprusinowski) [inline app/charts/shared/containers.tsx:25]: Nit: @noahonyejese it looks like the height is 20 on desktop, but 18 on mobile. This is a nit, but one way we could solve it would be to use:

```typescript
<Box
  component="foreignobject"
  width={...}
  sx={{ display: "flex", y: [18, 20], height: 24, textAlign: "right" }}
>
```

Also, maybe adding a little bit of padding to the bottom, like `height: 26` would make it less crowded? 🤔 

Screenshot 2024-11-12 at 10 09 10

File: app/components/publish-actions.tsx [hunk 2]
```diff
@@ -298,68 +199,193 @@ const Share = ({ configKey, locale }: PublishActionProps) => {
...
-                })
-              )}: ${shareUrl}`}
-            ></IconLink>
-          </Flex>
+      <ShareContent configKey={configKey} locale={locale} />
+    </TriggeredPopover>
+  );
+};
+
+type EmnbedContentProps = {
```
Comment (bprusinowski) [inline app/components/publish-actions.tsx:207]: Typo: `Emnbed`

File: app/components/publish-actions.tsx [hunk 3]
```diff
@@ -38,7 +37,7 @@ export const PublishActions = (props: PublishActionProps) => {
 
 type TriggeredPopoverProps = {
   children: ReactNode;
-  renderTrigger: (
+  renderTrigger?: (
```
Comment (bprusinowski) [inline app/components/publish-actions.tsx:40]: @noahonyejese is there a case when this is actually undefined? By looking at the component name (`TriggeredPopover`), I'd assume that it should always be defined, otherwise the `Popover` can't be opened?

File: app/components/publish-actions.tsx [hunk 4]
```diff
@@ -298,68 +199,193 @@ const Share = ({ configKey, locale }: PublishActionProps) => {
...
+type EmnbedContentProps = {
+  iframeHeight: number;
+} & Omit<PublishActionProps, "chartWrapperRef">;
+
+export const EmbedContent = ({
+  locale,
+  configKey,
+  iframeHeight,
+}: EmnbedContentProps) => {
+  const [embedUrl, setEmbedUrl] = useState("");
```
Comment (bprusinowski) [inline app/components/publish-actions.tsx:216]: This is a personal opinion, but I think it was a bit more clear to have them inside one component, without a need to jump from `Embed` to `EmbedContent` – with the current approach, we need to have additional component, component props (with omitting some of them) and to pass them down, while the `Embed` and `Share` components are very bare-bone now and I think `Content` components are only used one inside their parents.

But it's okay like this, maybe there was some other reason I missed to separate them 👍

File: app/locales/de/messages.po [hunk 5]
```diff
@@ -1389,6 +1389,10 @@ msgstr "Duplizieren"
 msgid "login.chart.edit"
 msgstr "Bearbeiten"
 
+#: app/login/components/profile-tables.tsx
+msgid "login.chart.embed"
+msgstr "Einbetten"
+
```
Comment (bprusinowski) [inline app/locales/de/messages.po:1395]: So we ended up translating `Embed`? 🥲😅

File: app/locales/en/messages.po [hunk 6]
```diff
@@ -808,7 +808,7 @@ msgstr "An error happened while fetching possible filters, please retry later or
 
 #: app/configurator/components/dataset-control-section.tsx
 msgid "controls.section.datasets.title"
-msgstr "Data Sources"
+msgstr "Datasets"
```
Comment (bprusinowski) [inline app/locales/en/messages.po:811]: 👍

File: app/configurator/components/dataset-control-section.tsx [hunk 7]
```diff
@@ -233,7 +234,7 @@ export const DatasetsControlSection = () => {
   return (
     <ControlSection collapse defaultExpanded={false}>
       <SubsectionTitle titleId="controls-data" gutterBottom={false}>
-        <Trans id="controls.section.datasets.title">Data Sources</Trans>{" "}
+        <Trans id="controls.section.datasets.title">Dataset</Trans>{" "}
```
Comment (bprusinowski) [inline app/configurator/components/dataset-control-section.tsx:237]: `Datasets`?

**Review by bprusinowski — APPROVED** [review]
LGTM, thanks 💯

File: app/components/publish-actions.tsx (hunk 3 above)
Comment (noahonyejese) [reply app/components/publish-actions.tsx:40]: Yes sorry, I'm still working on one thing that potentially will be undefined, and use a trigger prop without rendering anything for, issue #1758

File: app/components/publish-actions.tsx (hunk 4 above)
Comment (noahonyejese) [reply app/components/publish-actions.tsx:216]: Yeah, sorry for the confusion I'm currently working on issue #1758 which doesnt need the buttons, inside the user profile it's meant to have the same design but opened by a `MenuActionItem`

File: app/components/publish-actions.tsx (hunk 3 above)
Comment (bprusinowski) [reply app/components/publish-actions.tsx:40]: Right, but then maybe it could be solved with `{shouldRenderTriggeredPopover && <TriggeredPopover {...} />}` and not with making the thing that controls the popover state undefined, as then it would never be shown if I am not mistaken? 🤔 Maybe I still miss something, sorry 😅

File: app/components/publish-actions.tsx (hunk 4 above)
Comment (bprusinowski) [reply app/components/publish-actions.tsx]: I see, thanks for clarifying 👍

**Comment by sosiology** [comment]
@noahonyejese for #1800 i noticed that the data sources are now shown at the top but the accordion is closed per default - so it still requires user interaction (opening the accordion) before the data set selected is visible, can we per default show the accordion open?

**Comment by noahonyejese** [comment]
@bprusinowski I will be wrapping this up a new PR

**Comment by KerstinFaye** [comment]
> Proposals: @KerstinFaye should we remove the Beta flag or the notification (1) from the section I think especially the (1) is drawing enormous attention towards it causing it to be opened even tho this may not be something the user will want to use straight away?

@noahonyejese thanks Noah, yes. I think we could remove it now. @bprusinowski, @sosiology any opinion on this?

**Comment by bprusinowski** [comment]
@KerstinFaye I would wait until we finalize merging of cubes improvements. As we realistically won't have a new PROD release before they are completed, should be fine to wait a bit?

We still need to wrap up https://github.com/visualize-admin/visualization-tool/pull/1849 and the grouped filters, drop-down options and table charts, right?

**Comment by sosiology** [comment]
Agree to keep the beta label until we have completed the improvements. Also, we are still waiting on feedback about the proposed placement at the top of the sidebar.
