### PR TITLE
fix: Application crash when using shared weekly date filter

### LINKED ISSUE #2013: Adding Global Filter results in application error
**Description**
When trying to add global filters in a dashboard layout, the application crashes. 

**Steps to reproduce**
1. Go to [this dashboard](https://int.visualize.admin.ch/de/v/w2xs9yYNtQez)
2. Copy and edit chart
3. Proceed to layout options and select dashboard -> free canvas (can also be reproduced with tab layout or other dashboard layouts)
5. See that Shared filters for `Date`and `Type` are shown
6. Activate Date filter and see that fields are empty per default (show dd.mm.yyyy as oppose to a value)
7. Click the date icon to set a date
8. See application error 

Image

Screenshot
https://github.com/user-attachments/assets/2d6f9459-9db8-4982-b778-a7b3807eaefb

Additional Context: 
Not sure if this could have something to do with how the dates are defined in the dataset (weeks). I noticed when trying to add an animation to the chart it was also not possible, even though there is a temporal dimension (date)

### PR DESCRIPTION
**Pull request by bprusinowski**
Closes #2013

This PR fixes a week-based temporal dimensions parsing in dashboard shared filters.

## How to test

1. Go to [this link](https://visualization-tool-git-fix-week-dates-global-filter-ixt1.vercel.app/en/create/new?cube=https://health.ld.admin.ch/fsvo/Moderhinke_Untersuchungsperiode_2024_2025/10&dataSource=Prod).
2. Add a second chart.
3. Proceed to layout options.
4. Enable `Date` shared filter.
5. ✅ See that the fields are filled in correctly.
6. ✅ See that you can interact with the date picker and the application doesn't break.

## How to reproduce
See instructions in #2013.

---

- [x] Add a CHANGELOG entry
- [x] Add an end-to-end test

### CODE REVIEW

File: app/rdf/mappings.ts [hunk 1]
```diff
@@ -26,7 +26,7 @@ export const timeFormats = new Map<string, string>([
 export const timeUnitFormats = new Map<TimeUnit, string>([
   [TimeUnit.Year, "%Y"],
   [TimeUnit.Month, "%Y-%m"],
-  [TimeUnit.Week, "%Y-%W"],
+  [TimeUnit.Week, "%Y-%m-%d"],
```
Comment (noahonyejese) [inline app/rdf/mappings.ts:29]: 👍

**Review by noahonyejese — APPROVED** [review]
LGTM, well done 🎉
