### PR TITLE
fix: Fixed tooltip for Mobile Area Charts

### LINKED ISSUE #94: Data Filter after Publication - unexpected error
Data Filter no longer work once the graph is published

image
image
image

### PR DESCRIPTION
**Pull request by noahonyejese**
@bprusinowski please check if this is the correct approach, if so I will continue implementing this for all charts and for tooltips that are larger the arrow will have to be more dynamic of course.

This PR: 
- Fixes Mobile Tooltip for all Chart except (Pie Charts, Scatterplot Charts, Map Charts)
- The exceptions still need design criteria, @KerstinFaye 
- This PR also uncovered a new Issue [#110](https://github.com/visualize-admin/visualization-tool-private/issues/110)
- This PR is the start to fix Issue [#94](https://github.com/visualize-admin/visualization-tool-private/issues/94)

This PR will resolve #94

---
### How to Test
1. Go to this [Visit Preview](https://vercel.live/open-feedback/visualization-tool-git-fix-mobile-tooltip-positioning-ixt1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)
2. Use the Einmalvergütung für Photovoltaikanlagen Dataset (you can test almost all Chart types w/ this)

3. Select Bar Chart -> Publish -> See how the tooltip is at the bottom with adjusting arrow ✅
4. Select Line Chart -> Publish -> See how the tooltip is at the bottom with adjusting arrow ✅
5. Select Area Chart -> Publish -> See how the tooltip is at the bottom with adjusting arrow ✅
6. Select Scatter Chart -> Publish -> See how the tooltip is at the bottom with adjusting arrow, but not optimal design ✅
7. Select Pie Chart -> Publish -> See how the tooltip is not placed correctly on mobile (potential separate issue), but is highlighted correctly ✅
8. Select Dual Axis Line Chart -> Publish -> See how the tooltip is at the bottom with adjusting arrow, but not optimal design ✅
9. Select Column Line Chart -> Publish -> See how the tooltip is at the bottom with adjusting arrow ✅

---

CC: @KerstinFaye , @sosiology

### CODE REVIEW

File: app/charts/area/areas-state.tsx [hunk 1]
```diff
@@ -352,6 +353,9 @@ const useAreasState = (
   xScaleTimeRange.range([0, chartWidth]);
   yScale.range([chartHeight, 0]);
 
+  const theme = useTheme();
+  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
```
Comment (bprusinowski) [inline app/charts/area/areas-state.tsx:357]: Nit: As this logic is used across a few different places in the application already, it would be super-nice to extract to a `useIsMobile` hook :)

File: app/charts/area/areas-state.tsx [hunk 2]
```diff
@@ -372,18 +376,21 @@ const useAreasState = (
         formatNumber,
       });
       const xAnchor = xScale(getX(datum));
-      const yAnchor = normalize
+      const yNormalized = normalize
```
Comment (bprusinowski) [inline app/charts/area/areas-state.tsx:379]: Nit: The name of the variable is only correct in "half" of the cases (when `normalize` is true) 😄 Maybe it could be renamed to `yDesktopAnchor` to make a connection with how it's used afterwards?

**Review by bprusinowski — COMMENTED** [review]
The overall approach looks good to me, thank you @noahonyejese! There's another problem that probably was there before, that the tooltip can go out of the viewport – I wonder if we maybe can take a look at the same time?

Screenshot 2024-11-06 at 14 42 35

File: app/charts/area/areas-state.tsx (hunk 1 above)
Comment (noahonyejese) [reply app/charts/area/areas-state.tsx:357]: ah cool I thought so we had something I was searching for useMobile hahaha

**Comment by noahonyejese** [comment]
@bprusinowski yeah I think the issue you mentioned above will resolve once we implement dynamic arrows

File: app/charts/area/areas-state.tsx (hunk 1 above)
Comment (noahonyejese) [reply app/charts/area/areas-state.tsx:357]: Sure  👍

Comment (noahonyejese) [reply app/charts/area/areas-state.tsx:357]: @bprusinowski could you tell me an ideal place to put it?

**Comment by bprusinowski** [comment]
Ah, but here it's not about the arrow, but that the whole tooltip can go out of viewport 👀 But maybe I missed something 👍

**Comment by noahonyejese** [comment]
> Ah, but here it's not about the arrow, but that the whole tooltip can go out of viewport 👀 But maybe I missed something 👍

yeah technically good point its kinda both, where when we move the tooltip the arrow will be off and vise versa I will make sure it works once this is done

File: app/charts/area/areas-state.tsx (hunk 1 above)
Comment (bprusinowski) [reply app/charts/area/areas-state.tsx:357]: @noahonyejese '@/utils/use-is-mobile.ts'?

**Comment by noahonyejese** [comment]
@bprusinowski I think everything works here, except for the Pie Chart, Map Chart and Scatter Plot. I will be updating the description for testing

File: app/utils/use-is-mobile.ts [hunk 3]
```diff
@@ -0,0 +1,7 @@
+import { useMediaQuery, useTheme } from "@mui/material";
+
+export const useIsMobile = () => {
+  const theme = useTheme();
+  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
+  return isMobile;
+};
```
Comment (bprusinowski) [inline app/utils/use-is-mobile.ts:7]: 👍

File: app/charts/shared/interaction/tooltip-box.tsx [hunk 4]
```diff
@@ -123,19 +127,32 @@ export const TooltipBox = ({
...
   const [pos, posRef] = usePosition();
+
+  const [tooltipRef, tooltipWidth] = useResizeObserver<HTMLDivElement>();
+
+  const isMobile = useIsMobile();
+  const { width, height } = useSize();
+  const { chartWidth } = useChartBounds(width, margins, height);
+
+  const tooltipX = isMobile
+    ? toolTipXBoundary(x!, tooltipWidth, chartWidth)
```
Comment (bprusinowski) [inline app/charts/shared/interaction/tooltip-box.tsx:138]: Nit: `tooltipXBoundary` (everywhere else we use tooltip as a single word) 👀

File: app/charts/shared/interaction/tooltip-box.tsx [hunk 5]
```diff
@@ -158,9 +175,9 @@ export const TooltipBox = ({
                 height: 0,
                 borderStyle: "solid",
                 top: triangle.top,
-                right: triangle.right,
                 bottom: triangle.bottom,
-                left: triangle.left,
+                left: isMobile ? triangleX : triangle.left,
+                right: !isMobile ? triangle.right : undefined,
```
Comment (bprusinowski) [inline app/charts/shared/interaction/tooltip-box.tsx:180]: Nit: Would it make sense to move this logic to `mkTriangle` (could be changed to a `useTriangle` hook)? That's a nit, but I think it's not really clear why we have both `triangle.right` and `triangleX` and what is the difference between them. What do you think @noahonyejese? 🤔

File: app/charts/shared/interaction/tooltip-box.tsx [hunk 6]
```diff
@@ -348,3 +366,38 @@ const mkTriangle = (p: TooltipPlacement) => {
       };
   }
 };
+
+const toolTipXBoundary = (
+  value: number,
```
Comment (bprusinowski) [inline app/charts/shared/interaction/tooltip-box.tsx:371]: Nit: Value of what? 😄 Is this an `x` position?

File: app/charts/shared/interaction/tooltip-box.tsx [hunk 7]
```diff
@@ -348,3 +366,38 @@ const mkTriangle = (p: TooltipPlacement) => {
...
+  chartWidth: number
+) => {
+  return Math.max(
+    tooltipWidth / 2 - TRIANGLE_SIZE,
+    Math.min(chartWidth - tooltipWidth / 2 + TRIANGLE_SIZE, value)
+  );
+};
+
+const triangleXPos = (
+  value: number,
```
Comment (bprusinowski) [inline app/charts/shared/interaction/tooltip-box.tsx:382]: Nit: `getTriangleXPosition`, `x: number`?

File: app/charts/shared/interaction/tooltip-box.tsx [hunk 8]
```diff
@@ -348,3 +366,38 @@ const mkTriangle = (p: TooltipPlacement) => {
...
+  tooltipWidth: number,
+  chartWidth: number
+): number => {
+  const condition = chartWidth - tooltipWidth / 2 + TRIANGLE_SIZE < value;
```
Comment (bprusinowski) [inline app/charts/shared/interaction/tooltip-box.tsx:401]: Nit: A `condition` for what? 😄 I think we lack an intent in the variable name here. Is this about `isOverflowing`?

File: app/charts/combo/combo-line-dual-state.tsx [hunk 9]
```diff
@@ -165,7 +165,9 @@ const useComboLineDualState = (
         };
       })
       .filter(truthy);
-    const yAnchor = isMobile ? chartHeight : mean(values.map((d) => d.yPos));
+    const yAnchor = isMobile
+      ? chartHeight + 32
```
Comment (bprusinowski) [inline app/charts/combo/combo-line-dual-state.tsx:169]: Why 32? 😄 Maybe this should be `margin.bottom`?

File: app/charts/shared/interaction/tooltip-box.tsx [hunk 10]
```diff
@@ -383,6 +383,21 @@ const triangleXPos = (
   tooltipWidth: number,
   chartWidth: number
 ): number => {
+  if (chartWidth < tooltipWidth) {
+    const maxPosition = chartWidth + TRIANGLE_SIZE;
```
Comment (bprusinowski) [inline app/charts/shared/interaction/tooltip-box.tsx:387]: Nit: `xMax`?

**Review by bprusinowski — APPROVED** [review]
Thanks @noahonyejese, LGTM 👏 Just a few nit comments 👍

File: app/charts/shared/interaction/tooltip-box.tsx (hunk 5 above)
Comment (noahonyejese) [reply app/charts/shared/interaction/tooltip-box.tsx:180]: Yeah I felt the same way about this however moving it to `mkTriangle` would force me to change the `TooltipPlacement` type to accept a new unintuitive type that kinda makes the switch case in `mkTriangle` work and I'd have to change it on a chart level rather than on a tooltip level. 

What do you think @bprusinowski ?

File: app/charts/combo/combo-line-dual-state.tsx (hunk 9 above)
Comment (noahonyejese) [reply app/charts/combo/combo-line-dual-state.tsx:169]: ah sorry, still had that there temp.

File: app/charts/shared/interaction/tooltip-box.tsx (hunk 5 above)
Comment (bprusinowski) [reply app/charts/shared/interaction/tooltip-box.tsx:184]: Maybe moving it to `mkTriangle` is not the best idea, but then I'd try to find a better name for these variables, or reorganize the code a bit (to clearly see a difference between e.g. `triangle.right` or `.left` and `triangleX`) 🤔

Comment (noahonyejese) [reply app/charts/shared/interaction/tooltip-box.tsx:184]: Yeah that's a good idea

Comment (bprusinowski) [reply app/charts/shared/interaction/tooltip-box.tsx:184]: Yes, I think it's much better 🎉 The only thing would be maybe `dynamicTriangleXPosition` -> `mobileTriangleXPosition`? I think that technically, the desktop one (static) is also dynamic, as it's adjusts to where the mouse is, right? If so, maybe the desktop / mobile naming convention would make sense 👍

Comment (noahonyejese) [reply app/charts/shared/interaction/tooltip-box.tsx:184]: Yep good idea 👍🏽

**Comment by noahonyejese** [comment]
@sosiology , @KerstinFaye this is ready for testing please free to compare everything w/ the designs as well:
---
Design References:

- Scatterplot Chart: Added a ruler, but no highlighting. Position on Top if multiple Datapoints are in one line.
[Visual Design Scatterplot](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5850-2923&t=moajWfo6OPOxdE2X-4)

- Pie Chart: Added Highlight (border line). Position of the tooltip would stay in place.
 [Visual Design Pie Chart](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5847-48005&t=moajWfo6OPOxdE2X-4)

- Map Chart: Highlight is already implemented. Would keep this, but ruler not necessary since position of the Tooltip would stay in place. 
[Visual Design Map](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5850-3123&t=moajWfo6OPOxdE2X-4)
