### PR TITLE
fix: Upgrade demo cubes

### LINKED ISSUE #1498: version upgrade should also happen for embedded demo charts
**Describe the bug**
A clear and concise description of what the bug is. If it seems connected to some data problem (missing values, wrong parsing) please first check the cube in Cube Checker ([int](https://int.visualize.admin.ch/_cube-checker), [prod](https://visualize.admin.ch/_cube-checker)) to see if everything is fine there.

**To Reproduce**

1. Go to https://test.visualize.admin.ch/
4. Scroll down to demo charts
5. see version upgrade didn't happen
6. instead warning is displayed

**Expected behavior**
version upgrade like for all the embedded charts

**Environment (please complete the following information):**
- Visualize environment and version: v4.3.0 ([1b6f09c](https://github.com/visualize-admin/visualization-tool/commit/1b6f09cf6fcc76720050b864a69023a195dc2f34))

**Additional context**
regression of https://github.com/visualize-admin/visualization-tool/pull/1473

### PR DESCRIPTION
**Pull request by bprusinowski**
Fixes #1498

This PR adds automatic cube upgrades to demo charts.

### CODE REVIEW

File: app/homepage/examples.tsx [hunk 1]
```diff
@@ -1,231 +1,97 @@
...
+      <Example
+        queryKey="example2"
+        configuratorState={defaultState2}
+        headline={example2Headline}
+        description={example2Description}
+        reverse
+      />
+    </Box>
+  );
+};
```
Comment (ptbrowne) [inline app/homepage/examples.tsx:60]: 💯

**Review by ptbrowne — APPROVED** [review]
💯 Thanks !
