### PR TITLE
Sort filters by position

### LINKED ISSUE #770: Order not correct for Ordinal dimension in filkters
The order of the categories is no longer respected in the right filter (colour axis), whereas it was correct before the new release. In the left filter, the order is correct.

**To Reproduce**
1. Go to int.visualize.admin.ch
2. Search "Red List (latest survey, with %)
3. Select "Color" Dimension "Status"
4. Order of categories is not respected

image

It should be this order

image

**Environment (please complete the following information):**
 - Visualize environment and version: [INT v3.9.5 ([6063484]
 - Edge 

**Additional context**

### PR DESCRIPTION
**Pull request by ptbrowne**
Sort right panel filters by position. Fix #770.

I also refactored playwright selectors + actions to use the fixtures concept of Playwright. Playwright fixtures enables us to remove the context parameter from selectors and actions (Playwright detects the destructured `selectors` / `actions` from the `test` function, and instantiates fixtures for us, selectors and actions are themselves based on the `page` and `screen` fixtures).

### CODE REVIEW

File: e2e/actions.ts [hunk 1]
```diff
@@ -1,43 +1,54 @@
...
+  async (field: string) => {
+    const fieldLocator = await selectors.panels
+      .left()
+      .within()
+      .findByText(`${field}`);
+    await fieldLocator.click();
+    await selectors.panels
+      .right()
+      .within()
+      .findByText(field, undefined, { timeout: 3000 });
```
Comment (bprusinowski) [inline e2e/actions.ts:17]: 💯

File: e2e/symbol-layer-colors.spec.ts [hunk 2]
```diff
@@ -19,28 +19,23 @@ test("Selecting SymbolLayer colors> should be possible to select nominal dimensi
...
-  await (await selectors.mui.popover().findByText("production region")).click();
+  await actions.mui.selectOption("production region");
 
-  expect(
-    await (await selectors.chart.colorLegend()).locator("div").count()
-  ).toBe(6);
+  const legendItems = (await selectors.chart.colorLegendItems())
+  expect(await legendItems.count()).toBe(6);
+  const legendTexts = await legendItems.allTextContents()
+  expect(legendTexts).toEqual(['Alps', 'Jura', 'Plateau', 'Pre-Alps', 'Southern Alps', 'Switzerland'])
```
Comment (bprusinowski) [inline e2e/symbol-layer-colors.spec.ts:40]: 👌

File: e2e/symbol-layer-colors.spec.ts [hunk 3]
```diff
@@ -19,28 +19,23 @@ test("Selecting SymbolLayer colors> should be possible to select nominal dimensi
...
+  expect(count).toEqual(7);
 
-  await (await within(panelRight).findByText("None")).click();
-
-  // Select options open in portal
-  await (await selectors.mui.popover().findByText("production region")).click();
-
-  // allow select options to disappear to prevent re-selecting none
-  await sleep(3000);
+  await (await within(panelRight).findByText("Show layer")).click();
```
Comment (bprusinowski) [inline e2e/symbol-layer-colors.spec.ts:27]: Shouldn't this be "None"?

**Review by bprusinowski — APPROVED** [review]
LGTM, great that we don't have to pass the context to each selector now 💯

File: e2e/symbol-layer-colors.spec.ts (hunk 3 above)
Comment (bprusinowski) [reply e2e/symbol-layer-colors.spec.ts]: Looks really cool with the control section (Color) 👌
