### PR TITLE
fix: fixed color on dimensions change

### LINKED ISSUE #2149: Colors cannot be edited after Dimension is changed
**Describe the bug** 
When adding segmentation and switching between dimensions in the dropdown, the color selector does not work.. 

**To Reproduce** Steps to reproduce the behavior:

1. Go to int.visualize.admin.ch
2. Select a data set (for this example `Bodenbelastung durch Schwermetalle` was used)
3. Go to Segmentation -> Select dimension `Bemerkungen`
4. See filters and color "squares" appear, allowing the user to change the colors. ✅ 
5. Change the dimension in the dropdown to `Gemeinde`
6. See that the filters do not appear and when the user clicks on "Filter Bearbeiten" they cannot adjust the color. ❌ 
7. See the color palette can also not be changed ❌ 

**Expected behavior** A clear and concise description of what you expected to
happen.
- It should be possible to change the dimension, and then edit the filters / colors

**Screenshots or video** 
https://github.com/user-attachments/assets/cc365030-0682-461c-8ace-7c63bf1f0708

Image

**Environment (please complete the following information):**
- Visualize environment and version: INT v5.3.0 ([6a359a8](https://github.com/visualize-admin/visualization-tool/commit/6a359a8c8ab4e942b73a5584cb2e3abff96b3a7c))
- Browser and version: Chrome

**Additional context**
None

### PR DESCRIPTION
**Pull request by noahonyejese**
Closes #2149 

**What changes?**
This PR fixes the color palette selection to persist and map correctly when changing dimensions

## How to test

1. Go to this link 
2. Create a chart (e.g : Bodenbelastung durch Schwermetalle)
3. Add Segmentation select (Bemerkungen)
4. Select a color palette
5. Change Dimension to (Gemeinde)
6. See how colors persist ✅

## How to reproduce
1. Go to this [link](https://test.visualize.admin.ch) 
2. Create a chart (e.g : Bodenbelastung durch Schwermetalle)
3. Add Segmentation select (Bemerkungen)
4. Select a color palette
5. Change Dimension to (Gemeinde)
6. See how colors don't persist ❌

---

- [x] Add a CHANGELOG entry

### CODE REVIEW

**Review by bprusinowski — COMMENTED** [review]
Thanks for taking a look @noahonyejese 💯 I don't have comments on the code, but looks like something broke after this PR, see the failed end-to-end tests (looks like the multi-filter panel doesn't display values anymore)?

https://app.argos-ci.com/interactive-things/visualization-tool/builds/456/140924292

**Comment by noahonyejese** [comment]
@bprusinowski is this ok?

File: app/configurator/components/filters.tsx [hunk 1]
```diff
@@ -533,31 +533,32 @@ const useEnsureUpToDateColorMapping = ({
...
+      activeField
     ) {
       dispatch({
         type: "CHART_CONFIG_UPDATE_COLOR_MAPPING",
         value: {
           dimensionId,
           colorConfigPath,
           colorMapping,
-          field: activeField,
+          field: isColorInConfig(chartConfig) ? "color" : activeField,
```
Comment (bprusinowski) [inline app/configurator/components/filters.tsx:549]: @noahonyejese I'd extract this outside of the hook, see that now we have `chartConfig` in dependencies, and it will re-run every time we change anything in `chartConfig`, while we should only re-run if `field` changes. Does it make sense? :)

File: app/configurator/components/filters.tsx [hunk 2]
```diff
@@ -358,6 +358,8 @@ const MultiFilterContent = ({
   const visibleLegendProps = useLegendTitleVisibility();
   const chartSymbol = getChartSymbol(chartConfig.chartType);
 
+  console.log(valueGroups);
```
Comment (bprusinowski) [inline app/configurator/components/filters.tsx:361]: 👀

**Review by bprusinowski — APPROVED** [review]
👌
