### PR TITLE
fix: increased yAdjustment for axis labels

### LINKED ISSUE #1878: ✓✓ Long Titles Wrap but Cover the Chart
To reproduce, see https://int.visualize.admin.ch/en/v/wVfk4PSYRdYk?dataSource=Prod on a smaller screen – the Y axis titles are wrapped, but the chart is not shifted to the bottom, so they are covering the chart.

Image

### PR DESCRIPTION
**Pull request by noahonyejese**
**This PR:** 
- This PR increase yAdjustment for axis Titles, like this they stop overlapping 
- This PR resolves #1878 

### How to Test
1. Go to this [link](https://visualization-tool-git-fix-minor-bugs-ixt1.vercel.app/) 
2. Search Photo and Select (Einmalvergütung für Photovoltaikanlagen) Dataset
3. Select a Combo Chart type 
4. Select the longest titles for but indicators 
5. Publish the Chart resize your screen up to 350px
6. See how the Titles never overlap ✅

---

CC: @sosiology

### CODE REVIEW

File: app/charts/combo/combo-line-dual-state.tsx [hunk 1]
```diff
@@ -133,23 +134,11 @@ const useComboLineDualState = (
...
-      : TICK_FONT_SIZE + TITLE_VPADDING) *
-      2 -
-    TICK_FONT_SIZE * 2;
-
-  const topMarginAxisTitleAdjustment = 50 + axisTitleAdjustment;
+  const { topMarginAxisTitleAdjustment } = useAxisTitleAdjustments({
+    leftAxisTitle: variables.y.left.label,
+    rightAxisTitle: variables.y.right.label,
+    containerWidth: width,
+  });
```
Comment (bprusinowski) [inline app/charts/combo/combo-line-dual-state.tsx:141]: Nice 👍

**Comment by bprusinowski** [comment]
I'd also consider adding a CHANGELOG entry along the lines of improving overlapping logic for combo charts 👍

**Comment by noahonyejese** [comment]
> I'd also consider adding a CHANGELOG entry along the lines of improving overlapping logic for combo charts 👍

Alright I was not sure if this is too minor for the CHANGELOG
