### PR TITLE
fix: Chart tooltip issues

### LINKED ISSUE #1916: Pie Chart: tooltip (on mobile device)
I checked with this data set/chart https://test.visualize.admin.ch/en/v/PPVBPVb1eRp4?dataSource=Int with exceptionally long labels, and noticed some times they are cut off. 

Data Set : Animal Health statistics per Year and Diseases, Latest data update: 20.08.2024 11:43 (on INT)

image

_Originally posted by @sosiology in https://github.com/visualize-admin/visualization-tool/issues/1911#issuecomment-2498768629_

Reported by Bartosz on 24.01.2025: We also need to Check Iframes for positioning and performance. 

Image

### PR DESCRIPTION
**Pull request by bprusinowski**
Closes #1916

This PR:
- allows chart tooltip to wrap in case of long text, constraining it to the container its in,
- makes pie chart tooltip always positioned on top of the chart, closer to it than before, which should decrease a chance of going off the screen when in iframe embed mode,
- simplifies some code and uses correct chart state types in `TooltipInner` component.

# iframe cut tooltip issue

## How to test
1. Go to [this link](https://seleniumbase.io/w3schools/iframes).
2. Remove all content and paste the following instead.

```html
<!DOCTYPE html>
<html>
<body>

<h2>HTML Iframes (nested iframes)</h2>
<p>Use CSS width & height to specify the iframe size:</p>

<iframe src="https://visualization-tool-git-fix-tooltip-issues-ixt1.vercel.app/en/embed/Q48H8AbY6OU_" width="500px" style="height: 1183px; border: 0px #ffffff none;"  name="visualize.admin.ch"></iframe>

</body>
</html>
```
3. Hit the `Run` button.
4. ✅ Hover over the chart and see that the tooltip is visible.

Screenshot 2025-01-24 at 14 33 11

## How to reproduce
1. Go to this link.
2. Remove all content and paste the following instead.

```html
<!DOCTYPE html>
<html>
<body>

<h2>HTML Iframes (nested iframes)</h2>
<p>Use CSS width & height to specify the iframe size:</p>

<iframe src="https://test.visualize.admin.ch/en/embed/DaUquLE8ex_T" width="500px" style="height: 1186px; border: 0px #ffffff none;"  name="visualize.admin.ch"></iframe>

</body>
</html>
```
3. Hit the `Run` button.
4. ❌ Hover over the chart and see that the tooltip is almost not visible.

Screenshot 2025-01-24 at 14 33 59

# overflowing text issue

## How to test
1. Go to [this link](https://visualization-tool-git-fix-tooltip-issues-ixt1.vercel.app/en/v/hLPmRpdcLAyf?dataSource=Prod).
2. Reduce browser window width to "mobile".
3. ✅ Hover over the chart and see that the tooltip stays within the container and that the labels wrap.

## How to reproduce
1. Go to [this link](https://test.visualize.admin.ch/en/v/Fv1IWsdvALQl?dataSource=Prod).
2. Reduce browser window width to "mobile".
3. ❌ Hover over the chart and see that the tooltip goes beyond the container and that the labels don't wrap.

---

- [x] Add a CHANGELOG entry

### CODE REVIEW

**Comment by sosiology** [comment]
💯 thanks @bprusinowski!

**Review by squiles — APPROVED** [review]
LGTM 🚀

File: app/charts/shared/interaction/tooltip.tsx [hunk 1]
```diff
@@ -60,7 +77,7 @@ const TooltipInner = ({ d, type }: { d: Observation; type: TooltipType }) => {
     datum,
     values,
     withTriangle,
-  } = getAnnotationInfo(d as any);
+  } = getAnnotationInfo(d as Observation & PieArcDatum<Observation>, []);
```
Comment (noahonyejese) [inline app/charts/shared/interaction/tooltip.tsx:80]: 🤩

File: app/charts/pie/rendering-utils.ts [hunk 2]
```diff
@@ -43,25 +43,11 @@ export const renderPies = (
...
             handleMouseLeave();
-            select<SVGPathElement, RenderDatum>(this).call(
-              (s: Selection<SVGPathElement, RenderDatum, BaseType, unknown>) =>
-                maybeTransition(s, {
-                  transition,
-                  s: (g) => g.attr("stroke-width", 0),
-                  t: (g) => g.attr("stroke-width", 0),
-                })
-            );
+            select<SVGPathElement, RenderDatum>(this).attr("stroke-width", 0)
```
Comment (noahonyejese) [inline app/charts/pie/rendering-utils.ts:50]: really nice here

**Review by noahonyejese — APPROVED** [review]
LGTM 🎉
