### PR TITLE
fix: BLW cube issues

### LINKED ISSUE #2304: BLW Cubes: When merging cubes tag shows up repetitively
**Describe the bug** 
When merging BLW cubes, I noticed that sometimes the tags in the merging cubes modal can appear multiple time.

Image

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'int.visualize.admin.ch`
2. select data source - INT
3. Select dataset `Marktzahlen Ölsaaten - Jährliche Produktionsmengen`
4. Click on Add data set and see that the join dimension Date is selected. 
5. Search for the data set `Marktzahlen Ölsaaten - Jährliche Konsumentenpreise` add the dataset 
7. See that the date tag is shown multiple times.

**Expected behavior** 
The Date tag  only appear 1x

**Additional Context** 

Note: The issue only occurs when the data sets are filtered by using the search. If the user just browses through the shown list, the tag only appears 1x. Also if you only search for Ölsaaten, it only appears once

Image

**Environment (please complete the following information):**

- Visualize environment and version: [e.g. INT v4.9.4]
- Browser and version [e.g. Chrome 132]

**Additional context** Add any other context about the problem here.

### LINKED ISSUE #2313: BLW Cubes: X-Axis NaN
**Describe the bug**
On Safari and FF the BLW cubes are showing a NaN in the tooltip and x-axis. This issue is not occurring in Chrome.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://int.visualize.admin.ch/en/v/53Q4Rapdf8Cg?dataSource=Int in Safari or FF
4. See error in x-axis labels and tooltips.

**Expected behavior** 
The values should show up correctly as seen in the screenshot below

Image

**Screenshots or video** 

Image

**Environment (please complete the following information):**

- Visualize environment and version: INT [v5.7.7 (b1f2b9a)](https://github.com/visualize-admin/visualization-tool/commit/b1f2b9ac41c80fe6469ed74e6ba06b5a53bd1a3e)
- Browser and version Safari + FF

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by bprusinowski**
Fixes #2304
Fixes #2313

This PR fixes:
- an issue with NaN values in X axis and tooltip title for temporal entity dimensions,
- an issue with duplicated termset tags when search for cubes to merge.

## How to test

1. Go to [this link](https://visualization-tool-git-fix-blw-cubes-issues-ixt1.vercel.app/browse?dataset=https%3A%2F%2Fagriculture.ld.admin.ch%2Ffoag%2Fcube%2FOilseeds%2FProduction_Quantity_Year&dataSource=Int).
2. ✅ See that X axis tick labels and tooltip title are formatted correctly (no NaNs).
3. ✅ Switch to a bar chart and see that it looks ok too.
4. Click on Hinzufügen.
5. Search for `Marktzahlen Ölsaaten - Jährliche Konsumentenpreise`.
6. ✅ See that the tags are not duplicated.

---

- [x] I added a CHANGELOG entry
- [x] I made a self-review of my own code

### CODE REVIEW

File: app/rdf/query-search.ts [hunk 1]
```diff
@@ -56,10 +56,52 @@ export const mergeSearchCubes = (
...
+    return termsets.filter((termset) => {
+      if (seen.has(termset.iri)) {
+        return false;
+      }
+
+      seen.add(termset.iri);
+
+      return true;
+    });
+  };
```
Comment (ptbrowne) [inline app/rdf/query-search.ts:85]: Nit: I guess we could use uniqBy here.

**Review by ptbrowne — APPROVED** [review]
LGTM :+1:
