### PR TITLE
fix: Allow multiple identical labels in charts

### LINKED ISSUE #1015: Same labelled values across hierarchy
@ptbrowne thank you for your work and the first fix. it works great for entities of same place within the hierarchy tree.
However showing canton 'JU' and region 'Jura' those values are combined.

expected:
- [ ] distinct IRIs shall be treated as distinct values:
    <https://ld.admin.ch/canton/26> (canton 'JU') != <https://ld.admin.ch/dimension/bgdi/biota/productionregions/1> (region 'Jura')

- [ ] sort order shall be by (1) hierarchy tree and (2) auto [identifier] resulting in 
    ZH, BE, LU, ...,  Jura, Mittelland, ... , 
    which is basically a flattened view of children tree of `data.dataCubeByIri.dimensions[10].hierarchy`
  ```shell
  curl 'https://int.visualize.admin.ch/api/graphql' -H 'x-visualize-cache-control: no-cache' --data-raw $'{"query":"query DataCubeMetadataWithComponentValues($iri: String\u0021, $sourceType: String\u0021, $sourceUrl: String\u0021, $locale: String\u0021, $latest: Boolean, $filters: Filters) {\\n  dataCubeByIri(\\n    iri: $iri\\n    sourceType: $sourceType\\n    sourceUrl: $sourceUrl\\n    locale: $locale\\n    latest: $latest\\n  ) {\\n    iri\\n    title\\n    publisher\\n    publicationStatus\\n    expires\\n    identifier\\n    workExamples\\n    creator {\\n      iri\\n      __typename\\n    }\\n    landingPage\\n    dimensions(sourceType: $sourceType, sourceUrl: $sourceUrl) {\\n      ...dimensionMetadata\\n      ...hierarchyMetadata\\n      __typename\\n    }\\n    measures(sourceType: $sourceType, sourceUrl: $sourceUrl) {\\n      ...dimensionMetadata\\n      ...hierarchyMetadata\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment dimensionMetadata on Dimension {\\n  iri\\n  label\\n  description\\n  isNumerical\\n  isKeyDimension\\n  dataType\\n  order\\n  values(sourceType: $sourceType, sourceUrl: $sourceUrl, filters: $filters)\\n  unit\\n  related {\\n    iri\\n    type\\n    __typename\\n  }\\n  ...hierarchyMetadata\\n  ... on TemporalDimension {\\n    timeUnit\\n    timeFormat\\n    __typename\\n  }\\n  ... on NumericalMeasure {\\n    isCurrency\\n    currencyExponent\\n    resolution\\n    isDecimal\\n    __typename\\n  }\\n}\\n\\nfragment hierarchyMetadata on Dimension {\\n  hierarchy(sourceType: $sourceType, sourceUrl: $sourceUrl) {\\n    ...hierarchyValueFields\\n    children {\\n      ...hierarchyValueFields\\n      children {\\n        ...hierarchyValueFields\\n        children {\\n          ...hierarchyValueFields\\n          children {\\n            ...hierarchyValueFields\\n            children {\\n              ...hierarchyValueFields\\n              __typename\\n            }\\n            __typename\\n          }\\n          __typename\\n        }\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\nfragment hierarchyValueFields on HierarchyValue {\\n  value\\n  dimensionIri\\n  depth\\n  label\\n  alternateName\\n  hasValue\\n  position\\n  identifier\\n}\\n","operationName":"DataCubeMetadataWithComponentValues","variables":{"iri":"https://environment.ld.admin.ch/foen/nfi/C-616/cube/1","sourceType":"sparql","sourceUrl":"https://int.lindas.admin.ch/query","locale":"de"}}' 
  ```

image
using abbreviation shows the same picture
image
see also https://int.visualize.admin.ch/v/h8HMMR5YiMbf?dataSource=Int

cc @zellersabine @ortnever @adintegra @sosiology

_Originally posted by @Rdataflow in https://github.com/visualize-admin/visualization-tool/issues/978#issuecomment-1496285833_

### PR DESCRIPTION
**Pull request by ptbrowne**
@bprusinowski is the author of the PR.

Fixes #1015.

This PR changes the way we index observations from indexing by label (or abbreviation) to indexing by value (for hierarchical dimensions, passed in a form of an additional property: `dimensionIri/__iri__`) or label (or abbreviation).

Basically, we change
`{ label_or_abbreviation: Observation }` into
`{ value_or_label_or_abbreviation: Observation }`.

We needed to make this change to allow displaying values with the same labels, which is now a case with hierarchical dimensions (but in most places, we are able to distinguish them anyway, either by a color legend below a chart or visually on the map).

There are also smaller bug fixes / improvements included:
- showing color legend when it makes sense for line chart (when there is more than one value)
- showing map legend when number of values > 1
- mouse interactions with overlapping shapes (map)
- added text stroke to `CircleLegend` labels
- added `dataSet` prop to `PublishedConfiguratorState` to fix loading hierarchies for `ColorLegend`

### How to test
1. Go to https://visualization-tool-git-fix-same-labelled-ixt1.vercel.app/en/v/QIhTScAJpRyN?dataSource=Int
2. See that we show Jura twice.
3. Copy and edit this visualization.
4. Change chart type to map.
5. See that both Jura regions are displayed on the map (and that they are colored correctly and that the tooltip interactions work).
6. Compare with https://int.visualize.admin.ch/en/v/eDRM5d2-KeD6?dataSource=Int
7. Follow steps 2-5 and see that the charts and interactions are broken.

### CODE REVIEW

File: app/charts/map/map.tsx [hunk 1]
```diff
@@ -383,10 +383,7 @@ export const MapComponent = () => {
           {...viewState}
         >
           <div data-map-loaded={loaded} />
-          <DeckGLOverlay
-            interleaved
-            layers={[geoJsonLayer, scatterplotLayer]}
-          />
```
Comment (ptbrowne) [inline app/charts/map/map.tsx:397]: Seems like you introduced it in response https://github.com/visualize-admin/visualization-tool/issues/713, could you quickly make sure that there is no problem ?

Comment (ptbrowne) [reply app/charts/map/map.tsx:397]: https://github.com/visualize-admin/visualization-tool/pull/1019/commits/2f63295ecaa85fe5bbd49ba38aa5e4b355c03b49 🤞

**Review by bprusinowski — APPROVED** [review]
🗺️
